#! /usr/local/bin/node
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var _ = require('lodash');
var lib = require('./lib');

var findTheDifference = function(s, t) {
  var sort = function(a, b){
    return lib.str.indexOf(a) - b;
  };
  s = s.split('');
  t = t.split('');

  s.sort(sort);
  t.sort(sort);
  var rzt = '';
  for(var i = 0 ; i < t.length; i++) {
    if (!s[i] || s[i] != t[i]) {
      rzt = t[i];
    }
  }
  return rzt;
};


var test = () => {
  var len = 10000000;
  var s = lib.genStr(len);
  var t = lib.genT(s);
  console.time('test');
  var rzt = findTheDifference(s, t);
  // var rzt = findTheDifference('abcd', 'abcde');
  console.log(`rzt: ${rzt}`);
  console.timeEnd('test');
}

test();