#! /usr/local/bin/node

/**
 * @param {number} a
 * @param {number} b
 * @return {number}
 */
var getSum = function(a, b) {
  return b === 0 ? a : getSum(a ^ b, (a & b) << 1);
};

console.log(getSum(1,3));
console.log(getSum(1,2));
console.log(getSum(1,1));
console.log(getSum(1,4));
console.log(getSum(1,5));
console.log(getSum(1,6));