#! /usr/local/bin/node
'use strict';

/**
 * @param {string} s
 * @return {string}
 */
var reverseString = function(s) {
  var rzt = '';
  for(var i = s.length - 1; i >= 0; i--) {
    rzt += s[i];
  }
  return rzt;
};

console.log(reverseString('hello'))